import {
    ArrowLeftRight,
    Box,
    Building2,
    Cable,
    Calculator,
    CircuitBoard,
    Circle,
    Code2,
    Cog,
    Columns3,
    CreditCard,
    Cylinder,
    Droplets,
    Drill,
    Factory,
    FileText,
    Flame,
    FlaskConical,
    Folder,
    Gauge,
    Heart,
    LayoutDashboard,
    LayoutGrid,
    Leaf,
    Lightbulb,
    Percent,
    Receipt,
    RectangleHorizontal,
    RotateCw,
    Ruler,
    Scale,
    Square,
    StepForward,
    Store,
    Sun,
    Thermometer,
    Timer,
    TrendingUp,
    Triangle,
    Weight,
    Zap,
  } from 'lucide-react';
  import type { LucideIcon } from 'lucide-react';
  
  const icons: Record<string, LucideIcon> = {
    ArrowLeftRight,
    Box,
    Building2,
    Cable,
    Calculator,
    CircuitBoard,
    Circle,
    Code2,
    Cog,
    Columns3,
    CreditCard,
    Cylinder,
    Droplets,
    Drill,
    Factory,
    FileText,
    Flame,
    FlaskConical,
    Folder,
    Gauge,
    Heart,
    LayoutDashboard,
    LayoutGrid,
    Leaf,
    Lightbulb,
    Percent,
    Receipt,
    RectangleHorizontal,
    RotateCw,
    Ruler,
    Scale,
    Square,
    Stairs: StepForward,  // lucide'da Stairs yok, alias
    Store,
    Sun,
    Thermometer,
    Timer,
    TrendingUp,
    Triangle,
    Weight,
    Zap,
  };
  
  export function getIcon(name: string | undefined, fallback: LucideIcon = Folder): LucideIcon {
    if (!name) return fallback;
    return icons[name] || fallback;
  }
  
  export { Folder, Calculator };
