<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>WinExe</OutputType>
    <AssemblyName>CriticalKRuntime</AssemblyName>
    <RootNamespace>Tooldur.CriticalKRuntime</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SolidWorks.Interop.sldworks" Version="32.1.0" />
  </ItemGroup>
</Project>
