import { NextResponse } from 'next/server';

export const runtime='nodejs';
export const dynamic='force-dynamic';

const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36';
const BASE='https://www.lcw.com';
const SOURCES={
  merve:{base:`${BASE}/kampanyalar/kadin-urunleri-sepette-yuzde-50-ye-varan-indirimli`,tag:'kadin-urunleri-sepette-yuzde-50-ye-varan-indirimli',categoryTreeId:null},
  oguzhan:{base:`${BASE}/kampanyalar/erkek-urunleri-sepette-yuzde-50-ye-varan-indirimli`,tag:'erkek-urunleri-sepette-yuzde-50-ye-varan-indirimli',categoryTreeId:null},
  ege:{base:`${BASE}/erkek-cocuk-giyim-t-200046`,tag:null,categoryTreeId:'200046'},
} as const;

type Profile=keyof typeof SOURCES;
type Product={external_id:string|null;title:string;url:string;image_url:string|null;current_price:number|null;original_price:number|null;discount_percent:number;in_stock:boolean|null;brand:string|null;source:string;profile_verified:boolean;matched_sizes:string[]};
const headers={'user-agent':UA,'accept':'text/html,application/xhtml+xml,application/json','accept-language':'tr-TR,tr;q=0.9,en;q=0.7','cache-control':'no-cache'};
function n(v:any):number|null{if(typeof v==='number'&&Number.isFinite(v))return v>0?v:null;if(typeof v!=='string')return null;let x=v.replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!x)return null;if(x.includes(',')&&x.includes('.'))x=x.lastIndexOf(',')>x.lastIndexOf('.')?x.replace(/\./g,'').replace(',','.'):x.replace(/,/g,'');else if(x.includes(','))x=x.replace(',','.');const z=Number(x);return Number.isFinite(z)&&z>0?z:null}
function abs(v:any){try{return v?new URL(String(v),BASE).toString():''}catch{return''}}
function one(v:any){return Array.isArray(v)?v[0]:v}
function balancedArray(text:string,start:number):string|null{let depth=0,inString=false,escaped=false;for(let i=start;i<text.length;i++){const c=text[i];if(inString){if(escaped){escaped=false;continue}if(c==='\\'){escaped=true;continue}if(c==='"')inString=false;continue}if(c==='"'){inString=true;continue}if(c==='[')depth++;else if(c===']'){depth--;if(depth===0)return text.slice(start,i+1)}}return null}
function findCatalogItemsInText(raw:string):any[]{for(const text of [raw,raw.replace(/\\"/g,'"')]){for(const marker of ['"CatalogList":{"Items":[','"CatalogList": {"Items": [','"Items":[{"HasCampaignBanners"']){const markerPos=text.indexOf(marker);if(markerPos<0)continue;const itemsPos=text.indexOf('"Items"',markerPos);const start=text.indexOf('[',itemsPos>=0?itemsPos:markerPos);if(start<0)continue;const arr=balancedArray(text,start);if(!arr)continue;try{const parsed=JSON.parse(arr);if(Array.isArray(parsed)&&parsed.length)return parsed}catch{}}}return[]}
function findCatalogItemsObject(root:any):any[]{const seen=new Set<any>();const walk=(x:any):any[]=>{if(!x||typeof x!=='object'||seen.has(x))return[];seen.add(x);if(Array.isArray(x?.CatalogList?.Items)&&x.CatalogList.Items.length)return x.CatalogList.Items;if(Array.isArray(x?.Items)&&x.Items.length&&x.Items.some((y:any)=>y?.ModelUrl||y?.ProductDescription))return x.Items;for(const v of Object.values(x)){const found=walk(v);if(found.length)return found}return[]};return walk(root)}
function findCatalogItems(raw:string):any[]{try{const j=JSON.parse(raw);const fromObj=findCatalogItemsObject(j);if(fromObj.length)return fromObj}catch{}return findCatalogItemsInText(raw)}
function extractFilters(html:string){const text=html.replace(/\\"/g,'"');const out=new Map<string,Set<string>>();const re=/"Value":(\d+),"Text":"([^"]+)"/g;let m:RegExpExecArray|null;while((m=re.exec(text))){const label=m[2].trim();if(!out.has(label))out.set(label,new Set());out.get(label)!.add(m[1])}return out}
function targetFilter(profile:Profile,filters:Map<string,Set<string>>){if(profile==='merve'){const labels=['L','XL'];return{labels,ids:labels.flatMap(x=>[...(filters.get(x)||[])])}}if(profile==='oguzhan'){const labels=['XL'];return{labels,ids:[...(filters.get('XL')||[])]}}const labels:string[]=[];const ids:string[]=[];for(const [label,values] of filters){const m=label.match(/^(\d+)(?:-(\d+))?\s*Yaş$/i);if(!m)continue;if(Number(m[1])<4)continue;labels.push(label);ids.push(...values)}return{labels,ids}}
function buildAjax(profile:Profile,ids:string[]){const cfg=SOURCES[profile];const size=ids.join(',');if(cfg.tag)return`${BASE}/tr/ajax/ProductList/ProductListPageData?xhrKeys=Tag,xhrKeys&Tag=${encodeURIComponent(cfg.tag)}&PageIndex=1&LastFilter=m_size&m_size=${size}`;return`${BASE}/tr/ajax/ProductList/ProductListPageData?xhrKeys=CategoryTreeId,xhrKeys&CategoryTreeId=${cfg.categoryTreeId}&PageIndex=1&LastFilter=m_size&m_size=${size}`}
function val(o:any,keys:string[]){for(const k of keys)if(o?.[k]!=null&&o[k]!=='')return o[k];return null}
function mapItem(item:any,profile:Profile,matched:string[]):Product|null{const url=abs(val(item,['ModelUrl','ProductUrl','Url','URL']));if(!url)return null;const badgePrices=(item?.CampaignBadges||[]).map((b:any)=>n(b?.DiscountedPrice)).filter((x:any):x is number=>x!==null);const rawPrices=[n(item?.DiscountedPriceValue),n(item?.DiscountedPrice),n(item?.OptionSalePrice),n(item?.SalePrice),n(item?.CurrentPrice),n(item?.CampaignPrice),n(item?.PriceValue),n(item?.Price)].filter((x):x is number=>x!==null);if(!rawPrices.length&&!badgePrices.length)return null;const current=Math.min(...badgePrices,...rawPrices);if(!Number.isFinite(current)||current<=0)return null;const originalCandidates=[n(item?.OldPrice),n(item?.OriginalPrice),n(item?.ListPrice),n(item?.MarketPrice),n(item?.PriceValue),...rawPrices].filter((x):x is number=>x!==null&&x>current);const original=originalCandidates.length?Math.max(...originalCandidates):null;const title=String(val(item,['ProductDescription','ProductName','ModelName','Title','Name','Description','SubTitleDescription'])||'LC Waikiki ürünü').trim();const img=val(item,['DefaultOptionImageUrl','DefaultOptionImage','ImageUrl','ImageURL'])||one(item?.OptionImageUrlList);const stock=n(val(item,['AvailableStock','Stock','StockQuantity']));const discount=original&&original>current?Math.round((1-current/original)*10000)/100:0;return{external_id:String(val(item,['OptionId','ModelId','ProductId','Id','OzelKodRenkKod'])||'')||null,title,url,image_url:img?abs(img):null,current_price:current,original_price:original,discount_percent:discount,in_stock:stock===null?null:stock>0,brand:String(item?.Brand||item?.BrandPropertyDescription||'LC Waikiki'),source:`lcw-profile-${profile}`,profile_verified:true,matched_sizes:matched}}
export async function GET(req:Request){const profile=(new URL(req.url).searchParams.get('profile')||'merve') as Profile;if(!(profile in SOURCES))return NextResponse.json({ok:false,error:'Geçersiz profil'},{status:400});try{const cfg=SOURCES[profile];const baseRes=await fetch(cfg.base,{cache:'no-store',redirect:'follow',headers});const baseHtml=await baseRes.text();if(!baseRes.ok)return NextResponse.json({ok:false,status:baseRes.status,error:'LCW kategori sayfası açılamadı',products:[]},{status:502});const filters=extractFilters(baseHtml);const target=targetFilter(profile,filters);const ids=[...new Set(target.ids)];if(!ids.length)return NextResponse.json({ok:false,error:'Uygun beden/yaş filtresi bulunamadı',profile,products:[]},{status:502});const ajaxUrl=buildAjax(profile,ids);const res=await fetch(ajaxUrl,{cache:'no-store',redirect:'follow',headers:{...headers,'x-requested-with':'XMLHttpRequest','referer':cfg.base}});const raw=await res.text();if(!res.ok)return NextResponse.json({ok:false,status:res.status,error:'LCW filtreli liste alınamadı',profile,products:[]},{status:502});const items=findCatalogItems(raw);const seen=new Set<string>();const products:Product[]=[];for(const item of items){const p=mapItem(item,profile,target.labels);if(!p||seen.has(p.url))continue;seen.add(p.url);products.push(p);if(products.length>=100)break}products.sort((a,b)=>b.discount_percent-a.discount_percent||Number(a.current_price)-Number(b.current_price));return NextResponse.json({ok:true,status:res.status,profile,source:'lcw-filtered',filter_labels:target.labels,filter_ids:ids,count:products.length,products,at:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}catch(e:any){return NextResponse.json({ok:false,error:String(e?.message||e),products:[]},{status:500})}}
