<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <AssemblyName>BaykalTools_PDM2024</AssemblyName>
    <RootNamespace>Tooldur.BaykalToolsHybrid</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BaykalToolsHybrid.cs" />
    <PackageReference Include="SolidWorks.EPDM.Interop.epdm" Version="32.1.0">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </PackageReference>
    <PackageReference Include="SolidWorks.Interop.sldworks" Version="32.1.0">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </PackageReference>
    <PackageReference Include="SolidWorks.Interop.swpublished" Version="32.1.0">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </PackageReference>
    <PackageReference Include="SolidWorks.Interop.swconst" Version="32.1.0">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </PackageReference>
  </ItemGroup>
</Project>
