<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <AssemblyName>Tooldur.BaykalSwAddin</AssemblyName>
    <RootNamespace>Tooldur.BaykalSwAddin</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ComVisible>true</ComVisible>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SolidWorks.Interop.sldworks" Version="32.1.0" />
    <PackageReference Include="SolidWorks.Interop.swpublished" Version="32.1.0" />
    <PackageReference Include="SolidWorks.Interop.swconst" Version="32.1.0" />
  </ItemGroup>
</Project>
